export const BLOGSETTINGS_UPDATED = 'BLOGSETTINGS_UPDATED'
export const BLOGMENU_UPDATED = 'BLOGMENU_UPDATED'
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'